vich_uploader:
    db_driver: orm

    mappings:
       cupcake_image:
           uri_prefix: /image/imgArticle
           upload_destination: '%kernel.project_dir%/public/image/imgArticle'
           namer : Vich\UploaderBundle\Naming\UniqidNamer
